site_name: !ENV [SITE_NAME, "ERGO"]
site_description: !ENV [SITE_DESCRIPTION, "Sitio estático para notas colaborativas"]
site_url: !ENV [SITE_URL, "https://tomasccc.github.io/"]

repo_url: !ENV [REPO_URL, "https://github.com/tomasccc/ergo-template"]
repo_name: !ENV [REPO_NAME, "tomasccc/ergo-template"]
edit_uri: !ENV [EDIT_URI, "edit/main/docs/"]

copyright: |
    Infraestructura bajo licencia AGPLv3. <br>
    Los apuntes se distribuyen bajo <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a>. <br>
    ERGO no se responsabiliza por el contenido subido por terceros en la sección Comunidad. <br><br>
    ☕ <strong>¿Te sirvió el sitio?</strong> Podés <a href="https://cafecito.app/ergonotes" target="_blank">colaborar con el mantenimiento del servidor acá</a>. 
theme:
  name: material
  custom_dir: overrides  
  logo: assets/logo.png
  favicon: assets/logo2.png  
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - navigation.prerender
    - search.highlight
    - search.share
    - search.full_text
    - search.math
    - search.suggest
    - navigation.indexes 
  font:
    text: Inter
    code: Inter
  palette:
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    - scheme: slate
      primary: black
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tomasccc
      name: Mi GitHub
    - icon: fontawesome/solid/mug-hot  
      link: https://cafecito.app/ergonotes 
      name: Invitame un café / Colaborar
  decap_proxy: https://decap-proxy.tomycaruso.workers.dev
  giscus:
    repo: tomasccc/ergo-template
    repo_id: R_kgDOPuzt5g
    category: Announcements
    category_id: DIC_kwDOPuzt5s4C3jEL

plugins:
  - search
  - awesome-pages 
  - macros      
  - tags:
      tags_file: tags.md
  - social:
      cards_layout_options:
        background_color: "#3f51b5"  
        color: "#ffffff"            
        font_family: Inter
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      fallback_to_build_date: true
  - git-committers:
      repository: !ENV [REPO_NAME, "tomasccc/ergo"] 
      branch: main

  - git-authors:
      show_contribution: true
      show_line_count: true        
      ignore_authors:
        - "dependabot[bot]"
        - "dependabot-preview[bot]"
        - "dependabot-core[bot]"
        - "dependabot"
        - "dependabot[bot]"
        - "dependabot-preview" 
        - "dependabot-core" 

hooks:
  - hooks.py

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true 
  - toc:
      permalink: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js